language: go

go:
  - 1.9

go_import_path: "./openauth"

notifications:
  email:
    recipients:
      - 18108053819@163.com
  on_success: change
  on_failure: always

addons:
  mariadb: '10.2'

before_install:
  - mysql -e "DROP DATABASE IF EXISTS openauth;"
  - mysql -e "CREATE DATABASE openauth;"
  - mysql -e "GRANT ALL PRIVILEGES ON openauth.* TO 'openauth'@'localhost' IDENTIFIED BY 'openauth';"
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - mysql -uopenauth -popenauth -Dopenauth < conf/ddl/openauthv01.sql
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken cjtC3u3ZHQZPLEJt6FgJS3LU6maKaGuYX


after_script:
  - mysql -e "DROP DATABASE IF EXISTS openauth"